## Главы 1 - 5

In [1]:
def neural_network(inp, weights):
    prediction = inp * weights
    return prediction

In [2]:
weights = 0.1
number_of_toes = [8.5, 9.5, 10, 9]
inp = number_of_toes[0]
pred = neural_network(inp, weights)
pred

0.8500000000000001

In [3]:
def w_sum(inp, weights):
    """Функция делает скалярное произведение векторов"""
    if not len(inp) == len(weights):
        raise Exception('Inputs and Weights don\'t have the same length!')
    else:
        result = 0
        for i in range(len(inp)):
            result += inp[i] * weights[i]
        return result

In [4]:
#w_sum([0.1, 0.1, 0.1, 0.1], [2, 2, 3])

### Несколько входов и один выход

In [5]:
class MyClass(object):
    def __init__(self, weights, toes, wlrec, nfans):
        self.weights = weights
        self.toes = toes
        self.wlrec = wlrec
        self.nfans = nfans
        
        
    def w_sum(self, inp, weights):
        if len(inp) != len(weights):
            raise Exception('ERROR!')
        result = 0
        for i in range(len(inp)):
            result += inp[i] * weights[i]
        return result 
    
    
    def elementwise_multiplication(self, vec_a, vec_b):
        if len(vec_a) != len(vec_b):
            raise Exception('ERROR!')
        result = []
        for i in range(len(vec_a)):
            result.append(vec_a[i] * vec_b[i])
        return result
            
        
    def elementwise_addition(self, vec_a, vec_b):
        if len(vec_a) > len(vec_b):
            vec_a, vec_b = vec_a, vec_b
        elif len(vec_a) < len(vec_b):
            vec_a, vec_b = vec_b, vec_a
        else:
            pass
        
        result = []
        for i in range(len(vec_a)):
            try:
                result.append(vec_a[i] + vec_b[i])
            except:
                result.append(vec_a[i])
        return result
    
    
    def vector_sum(self, vec_a):
        result = 0
        for i in range(len(vec_a)):
            result += vec_a[i]
        return result
    
    
    def vector_average(self, vec_a):
        result = 0
        for i in range(len(vec_a)):
            result += vec_a[i]
        return result/len(vec_a)
    
    
    def neural_network(self, inp, weights):
        prediction = self.w_sum(inp, weights)
        return prediction

In [6]:
weights = [0.1, 0.2, 0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inp = [toes[0], wlrec[0], nfans[0]]

class1 = MyClass(weights, toes, wlrec, nfans)

In [7]:
class1.w_sum(inp, weights)

0.9800000000000001

In [8]:
class1.elementwise_multiplication(inp, weights)

[0.8500000000000001, 0.13, 0.0]

In [9]:
class1.w_sum([class1.toes[0], class1.wlrec[0], class1.nfans[0]], class1.weights)

0.9800000000000001

In [10]:
class1.vector_sum(weights)

0.30000000000000004

In [11]:
class1.vector_average(weights)

0.10000000000000002

In [12]:
class1.neural_network(inp, weights)

0.9800000000000001

In [13]:
import numpy as np

### Один вход и несколько выходов

In [14]:
import numpy as np

In [15]:
class MyClass2(object):
    def __init__(self, weights, toes, wlrec, nfans):
        import numpy as np
        self.weights = weights
        self.toes = toes
        self.wlrec = wlrec
        self.nfans = nfans
        
    def ele_mul(self, vec_a, vec_b):
        return vec_a * vec_b  
    
    def neural_network(self, inp, weights):
        prediction = self.ele_mul(inp, weights)
        return prediction
    
    def neural_network_old(self, inp, weights):
        prediction = inp.dot(weights)
        return prediction

In [16]:
weights = np.array([0.3, 0.2, 0.9])
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inp = np.array([toes[0], wlrec[0], nfans[0]])

class2 = MyClass2(weights, toes, wlrec, nfans)
class2.neural_network_old(inp, weights)

3.76

In [17]:
inp = wlrec[0]
weights = np.array([0.3, 0.2, 0.9])
class2.ele_mul(inp, weights)

array([0.195, 0.13 , 0.585])

In [18]:
class2.neural_network(inp, weights)

array([0.195, 0.13 , 0.585])

### Несколько входов и несколько выходов ♥

In [19]:
inp = np.vstack([toes, wlrec, nfans]).T
inp

array([[8.5 , 0.65, 1.2 ],
       [9.5 , 0.8 , 1.3 ],
       [9.9 , 0.8 , 0.5 ],
       [9.  , 0.9 , 1.  ]])

In [20]:
inp = inp[0,:]
inp

array([8.5 , 0.65, 1.2 ])

In [21]:
weights = np.array([[0.1, 0.1, -0.3],
                    [0.1, 0.2,  0.0],
                    [0.0, 1.3,  0.1]]).T
weights

array([[ 0.1,  0.1,  0. ],
       [ 0.1,  0.2,  1.3],
       [-0.3,  0. ,  0.1]])

In [22]:
# weights = weights[:,0].reshape(-1,1)
# weights

In [23]:
class MyClass3(object):
    def __init__(self, inp, weights):
        import numpy as np
        self.inp = inp
        self.weights = weights

    
    def w_sum(self, inp, weights):
        inp = inp.reshape(-1,1).T
        weights = weights.reshape(-1,1).T
        if inp.shape[0] == weights.shape[0]:
            return np.sum(inp.ravel() * weights.ravel())
        else:
            raise Exception("Arrays have not equal shapes!")
    
    
    def vect_mat_mul(self, inp, weights):
        inp = inp.reshape(-1,1).T
        if inp.shape[1] == weights.shape[0]:
            output = np.zeros(inp.shape[1]).reshape(-1,1).T
            for i in range(weights.shape[1]):
                output[0,i] = self.w_sum(inp, weights[:,i])
            return output
        else:
            raise Exception("Arrays have not equal shapes!")
    
    
    def ele_mul(self, vec_a, vec_b):
        return vec_a * vec_b  
    
    
    def neural_network(self, inp, weights):
        prediction = self.vect_mat_mul(inp, weights)[0]
        return prediction
    
    
    def neural_network_old(self, inp, weights):
        prediction = self.ele_mul(inp, weights)
        return prediction
    
    
    def neural_network_oldest(self, inp, weights):
        prediction = inp.dot(weights)
        return prediction

In [24]:
class3 = MyClass3(inp, weights)
class3.neural_network(inp, weights)

array([0.555, 0.98 , 0.965])

### Скрытые слои (прогноз на основе прогноза) ♥

In [25]:
class MyClass4(object):
    def __init__(self, inp, weights):
        import numpy as np
        self.inp = inp
        self.weights = weights

    
    def w_sum(self, inp, weights):
        inp = inp.reshape(-1,1).T
        weights = weights.reshape(-1,1).T
        if inp.shape[0] == weights.shape[0]:
            return np.sum(inp.ravel() * weights.ravel())
        else:
            raise Exception("Arrays have not equal shapes!")
    
    
    def vect_mat_mul(self, inp, weights):
        inp = inp.reshape(-1,1).T
        if inp.shape[1] == weights.shape[0]:
            output = np.zeros(inp.shape[1]).reshape(-1,1).T
            for i in range(weights.shape[1]):
                output[0,i] = self.w_sum(inp, weights[:,i])
            return output
        else:
            raise Exception("Arrays have not equal shapes!")
    
    
    def ele_mul(self, vec_a, vec_b):
        return vec_a * vec_b  
    
    
    def neural_network(self, inp, weights):
        layer_1_pred = self.vect_mat_mul(inp, weights[0])[0].reshape(-1,1).T
        print('На внутренний слой подается:\n', layer_1_pred)
        prediction = self.vect_mat_mul(layer_1_pred, weights[1])[0]
        return prediction

In [26]:
inp = np.vstack([toes, wlrec, nfans]).T
inp

array([[8.5 , 0.65, 1.2 ],
       [9.5 , 0.8 , 1.3 ],
       [9.9 , 0.8 , 0.5 ],
       [9.  , 0.9 , 1.  ]])

In [27]:
inp = inp[0,:]
inp

array([8.5 , 0.65, 1.2 ])

In [28]:
hid_w = np.array([[0.1, 0.2, -0.1],
                  [-0.1,0.1,  0.9],
                  [0.1, 0.4,  0.1]]).T
hid_w

array([[ 0.1, -0.1,  0.1],
       [ 0.2,  0.1,  0.4],
       [-0.1,  0.9,  0.1]])

In [29]:
outer_w = np.array([[0.3, 1.1, -0.3],
                    [0.1, 0.2,  0.0],
                    [0.0, 1.3,  0.1]]).T
outer_w

array([[ 0.3,  0.1,  0. ],
       [ 1.1,  0.2,  1.3],
       [-0.3,  0. ,  0.1]])

In [30]:
weights = [hid_w, outer_w]
weights

[array([[ 0.1, -0.1,  0.1],
        [ 0.2,  0.1,  0.4],
        [-0.1,  0.9,  0.1]]), array([[ 0.3,  0.1,  0. ],
        [ 1.1,  0.2,  1.3],
        [-0.3,  0. ,  0.1]])]

In [31]:
class4 = MyClass4(inp, weights)
class4.neural_network(inp, weights)

На внутренний слой подается:
 [[0.86  0.295 1.23 ]]


array([0.2135, 0.145 , 0.5065])

### Среднеквадратическая ошибка

In [32]:
knob_weight = 0.5
inp = 0.5
goal_pred = 0.8

pred = inp * knob_weight
error = (pred - goal_pred) ** 2
print(round(error, 4))

0.3025


### Обучение методом "холодно-горячо"

In [33]:
weight = 0.1
lr = 0.01
def neural_network(inp, weight):
    prediction = inp * weight
    return prediction

In [34]:
number_of_toes = [8.5]
win_or_lose_binary = [1]

inp = number_of_toes[0]
true = win_or_lose_binary[0]

pred = neural_network(inp, weight)

error = (pred - true) ** 2
print(round(error, 4))

0.0225


Увеличим вес:

In [35]:
pred_up = neural_network(inp, weight + lr)
print('Текущий вес: ', round(weight + lr, 3))
print('Результат: ', round(pred_up, 4))
err_up = (pred_up - true) ** 2
print('RSE: ', round(err_up, 4))

Текущий вес:  0.11
Результат:  0.935
RSE:  0.0042


Уменьшим вес:

In [36]:
pred_dn = neural_network(inp, weight - lr)
print('Текущий вес: ', round(weight - lr, 3))
print('Результат: ', round(pred_dn, 3))
err_dn = (pred_dn - true) ** 2
print('RSE: ', round(err_dn, 3))

Текущий вес:  0.09
Результат:  0.765
RSE:  0.055


Сравним ошибки и выберем лучший результат (обновим вес)

In [37]:
if error != err_dn or error != err_up:
    if err_up > err_dn:
        weight -= lr
    elif err_up <= err_dn:
        weight += lr

In [38]:
print('Обновленный текущий вес: ', weight)

Обновленный текущий вес:  0.11


In [39]:
weight = 0.5 # начальный вес
lr = 0.001 # скорость обучения
def neural_network(inp, weight):
    prediction = inp * weight
    return prediction

number_of_toes = [0.5] # входящие данные
win_or_lose_binary = [0.8] # значение целевой переменной из наблюдения

inp = number_of_toes[0] # входящие данные
true = win_or_lose_binary[0] # значение целевой переменной из наблюдения

num_iters = 1200 + 1  # число итераций

for i in range(num_iters):
    pred = neural_network(inp, weight) # предсказание с текущим весом
    error = (pred - true) ** 2 # значение RSE

    pred_up = neural_network(inp, weight + lr) # предсказание с повышенным весом
    err_up = (pred_up - true) ** 2 # значение RSE
    
    pred_dn = neural_network(inp, weight - lr) # предсказание с пониженным весом
    err_dn = (pred_dn - true) ** 2 # значение RSE
    
    if error != err_dn or error != err_up: # в цикле выбираем новый вес
        if err_up > err_dn:
            weight -= lr
            if i % 50 == 0: # печатаем каждый 50-й шаг
                print('{}{: >3}'.format(list[x].ljust(15, ' '), x))
                print('iteration #{: >3} | prediction = {: >3}\
                |updated weight = {: >3} | RSE = {: >3} | dir DOWN'.format(i, round(pred_dn, 3), round(weight, 4), err_dn))
                print(f'iteration #{i} | prediction = {round(pred_dn, 3)} |updated weight = {round(weight, 4)} | RSE = {err_dn} | dir DOWN')
        elif err_up <= err_dn:
            weight += lr
            if i % 50 == 0: # печатаем каждый 50-й шаг
                print(f'iteration #{i} | prediction = {round(pred_up, 3)} |updated weight = {round(weight, 4)} | RSE = {err_up} | dir UP')

iteration #0 | prediction = 0.251 |updated weight = 0.501 | RSE = 0.3019502500000001 | dir UP
iteration #50 | prediction = 0.276 |updated weight = 0.551 | RSE = 0.27510025 | dir UP
iteration #100 | prediction = 0.301 |updated weight = 0.601 | RSE = 0.24950025 | dir UP
iteration #150 | prediction = 0.326 |updated weight = 0.651 | RSE = 0.22515024999999997 | dir UP
iteration #200 | prediction = 0.351 |updated weight = 0.701 | RSE = 0.20205024999999996 | dir UP
iteration #250 | prediction = 0.376 |updated weight = 0.751 | RSE = 0.18020024999999995 | dir UP
iteration #300 | prediction = 0.401 |updated weight = 0.801 | RSE = 0.15960024999999992 | dir UP
iteration #350 | prediction = 0.426 |updated weight = 0.851 | RSE = 0.1402502499999999 | dir UP
iteration #400 | prediction = 0.451 |updated weight = 0.901 | RSE = 0.1221502499999999 | dir UP
iteration #450 | prediction = 0.476 |updated weight = 0.951 | RSE = 0.1053002499999999 | dir UP
iteration #500 | prediction = 0.501 |updated weight = 1

In [40]:
weight = 0.5 # начальный вес
lr = 0.001 # скорость обучения
def neural_network(inp, weight):
    prediction = inp * weight
    return prediction

number_of_toes = [0.5] # входящие данные
win_or_lose_binary = [0.8] # значение целевой переменной из наблюдения

inp = number_of_toes[0] # входящие данные
true = win_or_lose_binary[0] # значение целевой переменной из наблюдения

num_iters = 1200 + 1  # число итераций

for i in range(num_iters):
    pred = neural_network(inp, weight) # предсказание с текущим весом
    error = (pred - true) ** 2 # значение RSE

    pred_up = neural_network(inp, weight + lr) # предсказание с повышенным весом
    err_up = (pred_up - true) ** 2 # значение RSE
    
    pred_dn = neural_network(inp, weight - lr) # предсказание с пониженным весом
    err_dn = (pred_dn - true) ** 2 # значение RSE
    
    if error != err_dn or error != err_up: # в цикле выбираем новый вес
        if err_up > err_dn:
            weight -= lr
            if i % 50 == 0: # печатаем каждый 50-й шаг
                str_list = ['iteration #', '| prediction = ', '| updated weight = ', '| RSE = ', '| dir DOWN']
                val_list = [i, round(pred_dn, 4), round(weight, 4), round(err_dn, 4), None]
                zip_list = [s for s in zip(str_list, val_list)]
                print('{}{: >4} {}{: >4} {}{: >4} {}{: >6}{}'.format(zip_list[0][0].ljust(15, ' '), zip_list[0][1], 
                                                                    zip_list[1][0].ljust(15, ' '), zip_list[1][1],
                                                                    zip_list[2][0].ljust(5, ' '), zip_list[2][1],
                                                                    zip_list[3][0].ljust(15, ' '), zip_list[3][1],))

        elif err_up <= err_dn:
            weight += lr
            if i % 50 == 0: # печатаем каждый 50-й шаг
                str_list = ['iteration #', '| prediction = ', '| updated weight = ', '| RSE = ', '| dir UP']
                val_list = [i, round(pred_up, 4), round(weight, 4), round(err_up, 4), None]
                zip_list = [s for s in zip(str_list, val_list)]
                print('{}{: >4} {}{: >4} {}{: >4} {}{: >6}{}'.format(zip_list[0][0].ljust(15, ' '), zip_list[0][1], 
                                                                    zip_list[1][0].ljust(15, ' '), zip_list[1][1],
                                                                    zip_list[2][0].ljust(15, ' '), zip_list[2][1],
                                                                    zip_list[3][0].ljust(5, ' '), zip_list[3][1],
                                                                    zip_list[4][0].ljust(15, ' '), zip_list[4][1],
                                                                   ))

iteration #       0 | prediction = 0.2505 | updated weight = 0.501 | RSE =  0.302| dir UP       
iteration #      50 | prediction = 0.2755 | updated weight = 0.551 | RSE = 0.2751| dir UP       
iteration #     100 | prediction = 0.3005 | updated weight = 0.601 | RSE = 0.2495| dir UP       
iteration #     150 | prediction = 0.3255 | updated weight = 0.651 | RSE = 0.2252| dir UP       
iteration #     200 | prediction = 0.3505 | updated weight = 0.701 | RSE = 0.2021| dir UP       
iteration #     250 | prediction = 0.3755 | updated weight = 0.751 | RSE = 0.1802| dir UP       
iteration #     300 | prediction = 0.4005 | updated weight = 0.801 | RSE = 0.1596| dir UP       
iteration #     350 | prediction = 0.4255 | updated weight = 0.851 | RSE = 0.1403| dir UP       
iteration #     400 | prediction = 0.4505 | updated weight = 0.901 | RSE = 0.1222| dir UP       
iteration #     450 | prediction = 0.4755 | updated weight = 0.951 | RSE = 0.1053| dir UP       
iteration #     500 | predicti

### Вычисление направления и величины ошибки

In [41]:
weight = 0.5
goal_pred = 0.8
inp = 0.5

for iteration in range(20):
    pred = inp * weight
    error = (pred - goal_pred) ** 2
    dir_and_amount = (pred - goal_pred) * inp
    weight -= dir_and_amount
    
    print(f'Error {round(error, 4)} Prediction {round(pred, 4)} dir_and_amount {round(dir_and_amount,4)} weight {round(weight,4)}')

Error 0.3025 Prediction 0.25 dir_and_amount -0.275 weight 0.775
Error 0.1702 Prediction 0.3875 dir_and_amount -0.2063 weight 0.9813
Error 0.0957 Prediction 0.4906 dir_and_amount -0.1547 weight 1.1359
Error 0.0538 Prediction 0.568 dir_and_amount -0.116 weight 1.252
Error 0.0303 Prediction 0.626 dir_and_amount -0.087 weight 1.339
Error 0.017 Prediction 0.6695 dir_and_amount -0.0653 weight 1.4042
Error 0.0096 Prediction 0.7021 dir_and_amount -0.0489 weight 1.4532
Error 0.0054 Prediction 0.7266 dir_and_amount -0.0367 weight 1.4899
Error 0.003 Prediction 0.7449 dir_and_amount -0.0275 weight 1.5174
Error 0.0017 Prediction 0.7587 dir_and_amount -0.0206 weight 1.5381
Error 0.001 Prediction 0.769 dir_and_amount -0.0155 weight 1.5535
Error 0.0005 Prediction 0.7768 dir_and_amount -0.0116 weight 1.5652
Error 0.0003 Prediction 0.7826 dir_and_amount -0.0087 weight 1.5739
Error 0.0002 Prediction 0.7869 dir_and_amount -0.0065 weight 1.5804
Error 0.0001 Prediction 0.7902 dir_and_amount -0.0049 weight 1

### Одна итерация градиентного спуска

In [42]:
weight = 0.1
alpha = 0.01 # то же, что и learning rate

def neural_network(inp, weight):
    prediction = inp * weight
    return prediction

number_of_toes = [8.5] # входящие данные
win_or_lose_binary = [1] # значение целевой переменной из наблюдения

inp = number_of_toes[0] # входящие данные
goal_pred = win_or_lose_binary[0] # значение целевой переменной из наблюдения

pred = neural_network(inp, weight)

error = (pred - goal_pred) ** 2

delta = pred - goal_pred
print('Delta (abs error): ', round(delta, 3))

weight_delta = inp * delta
print('Weight delta (grad): ', round(weight_delta, 3))

# вот оно, обучение
print('Initial weight: ', weight) 
weight -= weight_delta * alpha
print('Learned weight (weight - weight_delta * alpha): ', round(weight, 3))

Delta (abs error):  -0.15
Weight delta (grad):  -1.275
Initial weight:  0.1
Learned weight (weight - weight_delta * alpha):  0.113


In [43]:
# Обучаемся!
weight, goal_pred, inp, alpha = (.0, .8, .5, 1.)

for iteration in range(20):
    pred = neural_network(inp, weight)
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = inp * delta
    weight -= weight_delta * alpha
    print('Error (RSE): ', round(error, 4), ' Prediction: ', round(pred, 4))

Error (RSE):  0.64  Prediction:  0.0
Error (RSE):  0.36  Prediction:  0.2
Error (RSE):  0.2025  Prediction:  0.35
Error (RSE):  0.1139  Prediction:  0.4625
Error (RSE):  0.0641  Prediction:  0.5469
Error (RSE):  0.036  Prediction:  0.6102
Error (RSE):  0.0203  Prediction:  0.6576
Error (RSE):  0.0114  Prediction:  0.6932
Error (RSE):  0.0064  Prediction:  0.7199
Error (RSE):  0.0036  Prediction:  0.7399
Error (RSE):  0.002  Prediction:  0.7549
Error (RSE):  0.0011  Prediction:  0.7662
Error (RSE):  0.0006  Prediction:  0.7747
Error (RSE):  0.0004  Prediction:  0.781
Error (RSE):  0.0002  Prediction:  0.7857
Error (RSE):  0.0001  Prediction:  0.7893
Error (RSE):  0.0001  Prediction:  0.792
Error (RSE):  0.0  Prediction:  0.794
Error (RSE):  0.0  Prediction:  0.7955
Error (RSE):  0.0  Prediction:  0.7966


In [44]:
# Рассмотрим несколько цифлов обучения 
weight, goal_pred, inp, alpha = (0.0, 0.8, 1.1, 1.0)

for iteration in range(4):
    print("------\nWeight: " + str(weight))
    pred = inp * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = inp * delta
    weight -= weight_delta * alpha
    print('Error (RSE): ', round(error, 4), ' Prediction: ', round(pred, 4))
    print('Delta (abs err): ', round(delta, 4), ' Weight delta (grad): ', round(weight_delta, 4))

------
Weight: 0.0
Error (RSE):  0.64  Prediction:  0.0
Delta (abs err):  -0.8  Weight delta (grad):  -0.88
------
Weight: 0.8800000000000001
Error (RSE):  0.0282  Prediction:  0.968
Delta (abs err):  0.168  Weight delta (grad):  0.1848
------
Weight: 0.6951999999999999
Error (RSE):  0.0012  Prediction:  0.7647
Delta (abs err):  -0.0353  Weight delta (grad):  -0.0388
------
Weight: 0.734008
Error (RSE):  0.0001  Prediction:  0.8074
Delta (abs err):  0.0074  Weight delta (grad):  0.0081


### Ломаем градиентный спуск

In [45]:
weight, goal_pred, inp, alpha = (0.5, 0.8, 0.5, 1.0)

for iteration in range(20):
#     print("------\nWeight: " + str(weight))
    pred = inp * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = inp * delta
    weight -= weight_delta * alpha
    print('Error (RSE): ', round(error, 15), ' Prediction: ', round(pred, 4))
#     print('Delta (abs err): ', round(delta, 4), ' Weight delta (grad): ', round(weight_delta, 4))

Error (RSE):  0.3025  Prediction:  0.25
Error (RSE):  0.17015625  Prediction:  0.3875
Error (RSE):  0.095712890625  Prediction:  0.4906
Error (RSE):  0.053838500976563  Prediction:  0.568
Error (RSE):  0.030284156799316  Prediction:  0.626
Error (RSE):  0.017034838199616  Prediction:  0.6695
Error (RSE):  0.009582096487284  Prediction:  0.7021
Error (RSE):  0.005389929274097  Prediction:  0.7266
Error (RSE):  0.00303183521668  Prediction:  0.7449
Error (RSE):  0.001705407309382  Prediction:  0.7587
Error (RSE):  0.000959291611528  Prediction:  0.769
Error (RSE):  0.000539601531484  Prediction:  0.7768
Error (RSE):  0.00030352586146  Prediction:  0.7826
Error (RSE):  0.000170733297071  Prediction:  0.7869
Error (RSE):  9.6037479603e-05  Prediction:  0.7902
Error (RSE):  5.4021082276e-05  Prediction:  0.7927
Error (RSE):  3.038685878e-05  Prediction:  0.7945
Error (RSE):  1.7092608064e-05  Prediction:  0.7959
Error (RSE):  9.614592036e-06  Prediction:  0.7969
Error (RSE):  5.40820802e-06

In [46]:
# Демонстрируем пример расхождения, когда из-за больших инпутов сеть идет вразнос
weight, goal_pred, inp, alpha = (0.5, 0.8, 2.0, 1.0)

for iteration in range(20):
    pred = inp * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = inp * delta
    weight -= weight_delta * alpha
    print('Error (RSE): ', round(error, 15), ' Prediction: ', round(pred, 4))

Error (RSE):  0.04  Prediction:  1.0
Error (RSE):  0.36  Prediction:  0.2
Error (RSE):  3.239999999999998  Prediction:  2.6
Error (RSE):  29.159999999999986  Prediction:  -4.6
Error (RSE):  262.4399999999999  Prediction:  17.0
Error (RSE):  2361.959999999998  Prediction:  -47.8
Error (RSE):  21257.639999999978  Prediction:  146.6
Error (RSE):  191318.75999999983  Prediction:  -436.6
Error (RSE):  1721868.839999999  Prediction:  1313.0
Error (RSE):  15496819.559999991  Prediction:  -3935.8
Error (RSE):  139471376.03999993  Prediction:  11810.6
Error (RSE):  1255242384.3599997  Prediction:  -35428.6
Error (RSE):  11297181459.239996  Prediction:  106289.0
Error (RSE):  101674633133.15994  Prediction:  -318863.8
Error (RSE):  915071698198.4395  Prediction:  956594.6
Error (RSE):  8235645283785.954  Prediction:  -2869780.6
Error (RSE):  74120807554073.56  Prediction:  8609345.0
Error (RSE):  667087267986662.1  Prediction:  -25828031.8
Error (RSE):  6003785411879960.0  Prediction:  77484098.

In [47]:
# Вводим альфа
weight, goal_pred, inp, alpha = (0.5, 0.8, 2.0, 0.1)

for iteration in range(20):
    pred = inp * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    derivative = inp * delta
    weight -= derivative * alpha
    print('Error (RSE): ', round(error, 15), ' Prediction: ', round(pred, 4))

Error (RSE):  0.04  Prediction:  1.0
Error (RSE):  0.0144  Prediction:  0.92
Error (RSE):  0.005184  Prediction:  0.872
Error (RSE):  0.00186624  Prediction:  0.8432
Error (RSE):  0.0006718464  Prediction:  0.8259
Error (RSE):  0.000241864704  Prediction:  0.8156
Error (RSE):  8.707129344e-05  Prediction:  0.8093
Error (RSE):  3.1345665638e-05  Prediction:  0.8056
Error (RSE):  1.128443963e-05  Prediction:  0.8034
Error (RSE):  4.062398267e-06  Prediction:  0.802
Error (RSE):  1.462463376e-06  Prediction:  0.8012
Error (RSE):  5.26486815e-07  Prediction:  0.8007
Error (RSE):  1.89535254e-07  Prediction:  0.8004
Error (RSE):  6.8232691e-08  Prediction:  0.8003
Error (RSE):  2.4563769e-08  Prediction:  0.8002
Error (RSE):  8.842957e-09  Prediction:  0.8001
Error (RSE):  3.183464e-09  Prediction:  0.8001
Error (RSE):  1.146047e-09  Prediction:  0.8
Error (RSE):  4.12577e-10  Prediction:  0.8
Error (RSE):  1.48528e-10  Prediction:  0.8


In [48]:
# Поподбираем разные значения скорости обучения
%time

alphas = [10**(-n) for n in range(6)]

print('List of alpha ', alphas, '\n')

for alpha in alphas:
    print(f'Alpha={alpha}')
    weight, goal_pred, inp = (0.5, 0.8, 2.0,)
    for iteration in range(21):
        pred = inp * weight
        error = (pred - goal_pred) ** 2
        delta = pred - goal_pred
        derivative = inp * delta
        weight -= derivative * alpha

        if iteration % 5 == 0:
            print('Error (RSE): ', round(error, 15), ' Prediction: ', round(pred, 4))
    print()

Wall time: 0 ns
List of alpha  [1, 0.1, 0.01, 0.001, 0.0001, 1e-05] 

Alpha=1
Error (RSE):  0.04  Prediction:  1.0
Error (RSE):  2361.959999999998  Prediction:  -47.8
Error (RSE):  139471376.03999993  Prediction:  11810.6
Error (RSE):  8235645283785.954  Prediction:  -2869780.6
Error (RSE):  4.8630661836227686e+17  Prediction:  697356881.0

Alpha=0.1
Error (RSE):  0.04  Prediction:  1.0
Error (RSE):  0.000241864704  Prediction:  0.8156
Error (RSE):  1.462463376e-06  Prediction:  0.8012
Error (RSE):  8.842957e-09  Prediction:  0.8001
Error (RSE):  5.347e-11  Prediction:  0.8

Alpha=0.01
Error (RSE):  0.04  Prediction:  1.0
Error (RSE):  0.02659330543966  Prediction:  0.9631
Error (RSE):  0.017680097355176  Prediction:  0.933
Error (RSE):  0.011754305729228  Prediction:  0.9084
Error (RSE):  0.007814646062213  Prediction:  0.8884

Alpha=0.001
Error (RSE):  0.04  Prediction:  1.0
Error (RSE):  0.038428494940112  Prediction:  0.996
Error (RSE):  0.036918730584056  Prediction:  0.9921
Error

### Корректировка сразу нескольких весов и обобщение градиентного спуска

#### Обучение методом градиентного спуска с несколькими входами

In [56]:
class MyClass5(object):
    
    
    def __init__(self, weights, toes, wlrec, nfans, lr):
        import numpy as np
        self.weights = weights
        self.toes = toes
        self.wlrec = wlrec
        self.nfans = nfans
        self.lr = lr
        
    def ele_mul(self, vec_a, vec_b):
        return np.array(vec_a) * np.array(vec_b) 
    
    
    def w_sum(self, inp, weights):
        inp = np.array([inp]).ravel()
        weights = np.array([weights]).ravel()
        if inp.shape != weights.shape:
            raise Exception('ERROR!')
        
        return np.sum(inp * weights) 
    
    
    def error(self, pred, true):
        pred = np.array([pred]).ravel()
        true = np.array([true]).ravel()
        if pred.shape != true.shape:
            raise Exception('ERROR!')
                  
        return (pred - true) ** 2
    
   
    def delta(self, pred, true):
        return (pred - true)
    
    
    def weight_deltas(self, delta, inp):
        return self.ele_mul(delta, inp)
    
    
    def updated_weights(self, weights, weight_deltas, lr):
        return weights - weight_deltas*lr
        
    
    def neural_network(self, inp, weights, lr):
        prediction = self.w_sum(inp, weights)
        return prediction
    
    def printer(self, inp, weights, true, lr):
        pred = self.neural_network(inp, weights, lr)
        error = self.error(pred, true)[0]
        delta = self.delta(pred, true)
        weight_deltas = self.ele_mul(delta, inp)
        updated_weights = self.updated_weights(weights, weight_deltas, lr)
        
        print(f'pred = {np.round(pred, 5)}\
        \nerror = {np.round(error, 5)}\
        \ndelta = {np.round(delta, 5)}\
        \nweight_deltas = {np.round(weight_deltas, 5)}\
        \ncurrent_weights = {weights}\
        \nupdated_weights = {np.round(updated_weights, 5)}')

In [57]:
weights = [0.1, 0.2, -0.1]

win_or_lose_binary = [1,1,0,1]
true = win_or_lose_binary[0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

lr = 0.01

inp = [toes[0], wlrec[0], nfans[0]]

class5 = MyClass5(weights, toes, wlrec, nfans, lr)

In [58]:
class5.printer(inp, weights, true, lr)

pred = 0.86        
error = 0.0196        
delta = -0.14        
weight_deltas = [-1.19  -0.091 -0.168]        
current_weights = [0.1, 0.2, -0.1]        
updated_weights = [ 0.1119   0.20091 -0.09832]


#### Градиентный спуск с несколькими входами

In [99]:
weights = [0.1, 0.2, -0.1]

win_or_lose_binary = [1,1,0,1]
true = win_or_lose_binary[0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

lr = 1

inp = [toes[0], wlrec[0], nfans[0]]

In [100]:
class5.printer(inp, weights, true, lr)

pred = 0.86        
error = 0.0196        
delta = -0.14        
weight_deltas = [-1.19  -0.091 -0.168]        
current_weights = [0.1, 0.2, -0.1]        
updated_weights = [1.29  0.291 0.068]


In [101]:
weights = [0.1, 0.2, -0.1]

win_or_lose_binary = [1,1,0,1]
true = win_or_lose_binary[0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

lr = 0.01

inp = [toes[0], wlrec[0], nfans[0]]

In [102]:
class5.printer(inp, weights, true, lr)

pred = 0.86        
error = 0.0196        
delta = -0.14        
weight_deltas = [-1.19  -0.091 -0.168]        
current_weights = [0.1, 0.2, -0.1]        
updated_weights = [ 0.1119   0.20091 -0.09832]


In [103]:
# переопределим в MyClass5 метод printer, чтобы научить его делать итерации
class MyClass6(MyClass5):
    
    
    def printer(self, inp, weights, true, lr, iters):
        
        for i in range(iters):
            pred = self.neural_network(inp, weights, lr)
            current_weights = weights
            error = self.error(pred, true)
            delta = self.delta(pred, true)
            weight_deltas = self.ele_mul(delta, inp)
            weights = self.updated_weights(weights, weight_deltas, lr)
            
            print(f'iter: {i+1}')
            print(f'pred = {np.round(pred, 3)}\
            \nerror = {np.round(error, 3)}\
            \ndelta = {np.round(delta, 2)}\
            \nweight_deltas = {np.round(weight_deltas, 2)}\
            \ncurrent_weights = {current_weights}\
            \nupdated_weights = {np.round(weights, 3)}')
            print('-'*20)


weights = [0.1, 0.2, -0.1]

win_or_lose_binary = [1,1,0,1]
true = win_or_lose_binary[0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

lr = 0.01*1
iters = 3

inp = [toes[0], wlrec[0], nfans[0]]

class6 = MyClass6(weights, toes, wlrec, nfans, lr)
class6.printer(inp, weights, true, lr, iters)

iter: 1
pred = 0.86            
error = [0.02]            
delta = -0.14            
weight_deltas = [-1.19 -0.09 -0.17]            
current_weights = [0.1, 0.2, -0.1]            
updated_weights = [ 0.112  0.201 -0.098]
--------------------
iter: 2
pred = 0.964            
error = [0.001]            
delta = -0.04            
weight_deltas = [-0.31 -0.02 -0.04]            
current_weights = [ 0.1119   0.20091 -0.09832]            
updated_weights = [ 0.115  0.201 -0.098]
--------------------
iter: 3
pred = 0.991            
error = [0.]            
delta = -0.01            
weight_deltas = [-0.08 -0.01 -0.01]            
current_weights = [ 0.11498061  0.20114558 -0.09788509]            
updated_weights = [ 0.116  0.201 -0.098]
--------------------


#### Замораживание одного веса

In [104]:
# переопределим в MyClass6 метод weight_deltas, чтобы обнулять первый вес всегда независимо ни от чего
class MyClass7(MyClass6):
    
    def weight_deltas(self, delta, inp):
        wd = self.ele_mul(delta, inp)
        wd[0] = 0
        return wd
    
    
weights = [0.1, 0.2, -0.1]

win_or_lose_binary = [1,1,0,1]
true = win_or_lose_binary[0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

lr = 0.01*2
iters = 10

inp = [toes[0], wlrec[0], nfans[0]]

class7 = MyClass7(weights, toes, wlrec, nfans, lr)
class7.printer(inp, weights, true, lr, iters)

iter: 1
pred = 0.86            
error = [0.02]            
delta = -0.14            
weight_deltas = [-1.19 -0.09 -0.17]            
current_weights = [0.1, 0.2, -0.1]            
updated_weights = [ 0.124  0.202 -0.097]
--------------------
iter: 2
pred = 1.068            
error = [0.005]            
delta = 0.07            
weight_deltas = [0.57 0.04 0.08]            
current_weights = [ 0.1238   0.20182 -0.09664]            
updated_weights = [ 0.112  0.201 -0.098]
--------------------
iter: 3
pred = 0.967            
error = [0.001]            
delta = -0.03            
weight_deltas = [-0.28 -0.02 -0.04]            
current_weights = [ 0.11232245  0.2009423  -0.09826036]            
updated_weights = [ 0.118  0.201 -0.097]
--------------------
iter: 4
pred = 1.016            
error = [0.]            
delta = 0.02            
weight_deltas = [0.13 0.01 0.02]            
current_weights = [ 0.1178575   0.20136557 -0.09747894]            
updated_weights = [ 0.115  0.201 -0.098]
----

### Обуение методом градиентного спуска с несколькими выходами

In [112]:
# переопределим метод neural_network, чтобы на выходе был ответ в виде вектора, а не одного числа
# замораживать веса не будем, так что наследуемся от MyClass6
class MyClass8(MyClass6):
    
    def neural_network(self, inp, weights, lr):
        prediction = self.ele_mul(inp, weights)
        return prediction
    
    
weights = [0.3, 0.2, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]

hurt = [0.1, 0.0, 0.0, 0.1]
win = [1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

inp = wlrec[0]
true = [hurt[0], win[0], sad[0]]

lr = 0.1
iters = 2



class8 = MyClass8(weights, toes, wlrec, nfans, lr)
class8.printer(inp, weights, true, lr, iters)

iter: 1
pred = [0.195 0.13  0.585]            
error = [0.009 0.757 0.235]            
delta = [ 0.1  -0.87  0.49]            
weight_deltas = [ 0.06 -0.57  0.32]            
current_weights = [0.3, 0.2, 0.9]            
updated_weights = [0.294 0.257 0.868]
--------------------
iter: 2
pred = [0.191 0.167 0.565]            
error = [0.008 0.694 0.216]            
delta = [ 0.09 -0.83  0.46]            
weight_deltas = [ 0.06 -0.54  0.3 ]            
current_weights = [0.293825 0.25655  0.868475]            
updated_weights = [0.288 0.311 0.838]
--------------------


#### Обуение методом градиентного спуска с несолькими входами и выходами

In [292]:
weights = np.array([[0.1, 0.1, -0.3],
                    [0.1, 0.2,  0.0],
                    [0.0, 1.3,  0.1]]).T
weights

array([[ 0.1,  0.1,  0. ],
       [ 0.1,  0.2,  1.3],
       [-0.3,  0. ,  0.1]])

In [293]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

hurt = [0.1, 0.0, 0.0, 0.1]
win = [1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

inp = [toes[0], wlrec[0], nfans[0]]
true = [hurt[0], win[0], sad[0]]

lr = 0.01
iters = 2

In [294]:
# переопределим еще раз методы класса
class MyClass9(MyClass8):
    
    
    def error(self, pred, true):
        pred = np.array([pred]).ravel()
        true = np.array([true]).ravel()
                 
        return (pred - true) ** 2
    
   
    def delta(self, pred, true):
        return (pred - true)
    
    
    def vect_mat_mul(self, vec, matrix):
        vec = np.array(vec).reshape(1,-1)
        matrix = np.array(matrix)
        
        if vec.shape[1] != matrix.shape[0]:
            print('Error in array shape!')
        output = np.zeros((vec.shape))
        for i in range(vec.shape[1]):
            output[0, i] = np.sum(vec * matrix[:,i].reshape(1,-1))
        return output
    
    
    def outer_prod(self, vec_a, vec_b):
        vec_a = np.array(vec_a).reshape(-1,1)
        vec_b = np.array(vec_b).reshape(1,-1)
        return vec_a.dot(vec_b)
    
    
    def neural_network(self, inp, weights):
        prediction = self.vect_mat_mul(inp, weights)
        return prediction
    
    
    def updated_weights(self, weights, weight_deltas, lr):
        return weights - weight_deltas*lr
    
    
    def printer(self, inp, weights, true, lr, iters):
        
        for i in range(iters):
            pred = self.neural_network(inp, weights)
            current_weights = weights
            error = self.error(pred, true)
            delta = self.delta(pred, true)
            weight_deltas = self.outer_prod(delta, inp)
            weights = self.updated_weights(weights, weight_deltas, lr)
            
            print(f'iter: {i+1}')
            print(f'pred = {np.round(pred, 3)}\
            \nerror = {np.round(error, 3)}\
            \ndelta = {np.round(delta, 2)}\
            \nweight_deltas = \n{np.round(weight_deltas, 2)}\
            \ncurrent_weights = \n{current_weights}\
            \nupdated_weights = \n{np.round(weights, 3)}')
            print('-'*20)

In [301]:
np.round((np.array([0.555, 0.98,  0.965]) - true)**2, 3)

array([0.207, 0.   , 0.748])

In [298]:
true

[0.1, 1, 0.1]

In [304]:
class9 = MyClass9(weights, toes, wlrec, nfans, lr)
class9.printer(inp, weights, true, lr, iters)

iter: 1
pred = [[0.555 0.98  0.965]]            
error = [0.207 0.    0.748]            
delta = [[ 0.46 -0.02  0.87]]            
weight_deltas = 
[[ 3.87  0.3   0.55]
 [-0.17 -0.01 -0.02]
 [ 7.35  0.56  1.04]]            
current_weights = 
[[ 0.1  0.1  0. ]
 [ 0.1  0.2  1.3]
 [-0.3  0.   0.1]]            
updated_weights = 
[[ 0.061  0.097 -0.005]
 [ 0.102  0.2    1.3  ]
 [-0.374 -0.006  0.09 ]]
--------------------
iter: 2
pred = [[0.139 0.948 0.906]]            
error = [0.002 0.003 0.65 ]            
delta = [[ 0.04 -0.05  0.81]]            
weight_deltas = 
[[ 0.33  0.03  0.05]
 [-0.44 -0.03 -0.06]
 [ 6.85  0.52  0.97]]            
current_weights = 
[[ 0.061325   0.0970425 -0.00546  ]
 [ 0.1017     0.20013    1.30024  ]
 [-0.373525  -0.0056225  0.08962  ]]            
updated_weights = 
[[ 0.058  0.097 -0.006]
 [ 0.106  0.2    1.301]
 [-0.442 -0.011  0.08 ]]
--------------------


### MNIST

In [305]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images = x_train[0:1000]
labels = y_train[0:1000]

Using TensorFlow backend.


11493376/11490434 [==============================] - 13s 1us/step


In [308]:
images[:3]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [309]:
labels

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1, 5, 7, 1, 7, 1, 1, 6, 3, 0, 2,
       9, 3, 1, 1, 0, 4, 9, 2, 0, 0, 2, 0, 2, 7, 1, 8, 6, 4, 1, 6, 3, 4,
       5, 9, 1, 3, 3, 8, 5, 4, 7, 7, 4, 2, 8, 5, 8, 6, 7, 3, 4, 6, 1, 9,
       9, 6, 0, 3, 7, 2, 8, 2, 9, 4, 4, 6, 4, 9, 7, 0, 9, 2, 9, 5, 1, 5,
       9, 1, 2, 3, 2, 3, 5, 9, 1, 7, 6, 2, 8, 2, 2, 5, 0, 7, 4, 9, 7, 8,
       3, 2, 1, 1, 8, 3, 6, 1, 0, 3, 1, 0, 0, 1, 7, 2, 7, 3, 0, 4, 6, 5,
       2, 6, 4, 7, 1, 8, 9, 9, 3, 0, 7, 1, 0, 2, 0, 3, 5, 4, 6, 5, 8, 6,
       3, 7, 5, 8, 0, 9, 1, 0, 3, 1, 2, 2, 3, 3, 6, 4, 7, 5, 0, 6, 2, 7,
       9, 8, 5, 9, 2, 1, 1, 4, 4, 5, 6, 4, 1, 2, 5, 3, 9, 3, 9, 0, 5, 9,
       6, 5, 7, 4, 1, 3, 4, 0, 4, 8, 0, 4, 3, 6, 8,